M48
; DRILL file {KiCad (6.0.9)} date Mon Nov 21 22:18:42 2022
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2022-11-21T22:18:42+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.9)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
%
G90
G05
T1
X153.8Y-91.305
X159.58Y-91.305
X165.61Y-91.305
X171.39Y-91.305
T0
M30
